# This file is an end-to-end single-file pipeline.
# It does NOT require fusion_ti_outputs/fusion_ti_topics_documents.csv.
# Generated by merging reusable indicator functions and the PatentBERT dedup-clustering main flow.

from __future__ import annotations

import argparse
import hashlib
import http.client
import json
import math
import os
import re
import time
import unicodedata
import urllib.error
import urllib.request
import warnings
from bisect import bisect_right
from collections import Counter
from concurrent.futures import ThreadPoolExecutor, as_completed
from contextlib import nullcontext
from pathlib import Path

import numpy as np
import pandas as pd
try:
    from sklearn.feature_extraction.text import ENGLISH_STOP_WORDS
    from sklearn.neighbors import LocalOutlierFactor
    from sklearn.preprocessing import normalize
except ModuleNotFoundError as exc:
    ENGLISH_STOP_WORDS = set()
    LocalOutlierFactor = None
    normalize = None
    SKLEARN_IMPORT_ERROR = exc
else:
    SKLEARN_IMPORT_ERROR = None


BASE_DIR = Path(os.environ.get("FUSION_TOPIC_BASE_DIR", "/mnt/d/工作/核聚变卡脖子/Lens_IPC"))
BASE_DIR_RESOLVED = BASE_DIR.resolve()


def data_path(path: Path | str) -> Path:
    path = Path(path)
    resolved = path if path.is_absolute() else BASE_DIR / path
    try:
        resolved.resolve().relative_to(BASE_DIR_RESOLVED)
    except ValueError as exc:
        raise ValueError(f"Path must be under {BASE_DIR}: {resolved}") from exc
    return resolved


DEFAULT_MERGED_PATENTS_PATH = data_path("merged_patents.xlsx")
DEFAULT_MERGED_FAMILIES_SHEET = "merged_families"
DEFAULT_MERGED_FAMILIES_OUTPUT = data_path("merged_families_patentbert_topic_indicators.xlsx")
DEFAULT_DEEPSEEK_TOPIC_CACHE = data_path("fusion_ti_outputs/deepseek_cluster_topic_sentences.json")
DEFAULT_MIN_VALID_TOPIC_SIZE = 30
DEEPSEEK_TOPIC_SCHEMA_VERSION = 3

IPC_SUBCLASS_RE = re.compile(r"[A-HY][0-9]{2}[A-Z]")
YEAR_RE = re.compile(r"\b(19[0-9]{2}|20[0-9]{2})\b")


def read_table(path: Path, sheet_name: str | None = None) -> pd.DataFrame:
    suffix = path.suffix.lower()
    if suffix in {".xlsx", ".xls"}:
        return pd.read_excel(path, sheet_name=sheet_name or 0)
    if suffix == ".csv":
        return pd.read_csv(path, encoding="utf-8-sig")
    if suffix == ".txt":
        return pd.read_csv(path, sep="\t", encoding="utf-8-sig")
    raise ValueError(f"Unsupported input file type: {path.suffix}")


def parse_year(value: object) -> float:
    if pd.isna(value):
        return np.nan
    if isinstance(value, (int, float, np.integer, np.floating)):
        year = int(value)
        return float(year) if 1800 <= year <= 2100 else np.nan
    text = str(value)
    years = [int(match) for match in YEAR_RE.findall(text)]
    if not years:
        return np.nan
    return float(min(years))


def parse_ipc_subclasses(value: object) -> list[str]:
    if pd.isna(value):
        return []
    text = str(value).upper()
    text = (
        text.replace("\u2010", "-")
        .replace("\u2011", "-")
        .replace("\u2012", "-")
        .replace("\u2013", "-")
        .replace("\u2014", "-")
        .replace("\u2212", "-")
    )
    return IPC_SUBCLASS_RE.findall(text)


def subclasses_to_text(codes: list[str]) -> str:
    return "; ".join(sorted(set(codes)))


def safe_doc_id(row: pd.Series, index: int) -> str:
    for col in (
        "Family ID",
        "Representative Lens ID",
        "Lens ID",
        "Display Key",
        "Representative Display Key",
        "UT",
        "DOI",
        "ID",
        "PN",
    ):
        if col in row.index and pd.notna(row[col]) and str(row[col]).strip():
            return str(row[col]).split(";")[0].splitlines()[0].strip()
    return f"DOC_{index + 1:06d}"


def require_sklearn() -> None:
    if SKLEARN_IMPORT_ERROR is not None:
        raise ModuleNotFoundError(
            "This pipeline requires scikit-learn. Install it in the active Python environment "
            "before running PatentBERT topic scoring."
        ) from SKLEARN_IMPORT_ERROR


def compute_topic_embeddings(embeddings: np.ndarray, topic_ids: np.ndarray) -> tuple[pd.DataFrame, np.ndarray]:
    require_sklearn()
    topics = np.array(sorted(pd.Series(topic_ids).dropna().astype(int).unique()), dtype=int)
    doc_embeddings = normalize(np.asarray(embeddings, dtype=np.float64), norm="l2", axis=1)
    centroids = []
    for topic in topics:
        idx = np.where(topic_ids == topic)[0]
        centroids.append(doc_embeddings[idx].mean(axis=0))
    topic_matrix = normalize(np.vstack(centroids), norm="l2", axis=1)
    return pd.DataFrame({"topic_id": topics}), topic_matrix


def compute_representative_docs(
    docs: pd.DataFrame,
    embeddings: np.ndarray,
    topic_index: pd.DataFrame,
    topic_embeddings: np.ndarray,
    top_n: int = 5,
) -> pd.Series:
    require_sklearn()
    doc_embeddings = normalize(np.asarray(embeddings, dtype=np.float64), norm="l2", axis=1)
    titles = docs["TI_raw"].fillna("").astype(str).to_numpy()
    topic_ids = docs["topic_id"].astype(int).to_numpy()
    representatives: dict[int, str] = {}

    for pos, topic in enumerate(topic_index["topic_id"].astype(int).to_numpy()):
        idx = np.where(topic_ids == topic)[0]
        if len(idx) == 0:
            representatives[topic] = ""
            continue
        sims = doc_embeddings[idx] @ topic_embeddings[pos]
        selected = idx[np.argsort(-sims)[:top_n]]
        representatives[topic] = " || ".join(titles[i] for i in selected)
    return pd.Series(representatives)


def safe_text(value: object) -> str:
    if value is None:
        return ""
    try:
        if pd.isna(value):
            return ""
    except (TypeError, ValueError):
        pass
    return str(value)


def compact_text(value: object, max_chars: int = 800) -> str:
    text = normalize_space(safe_text(value))
    if len(text) <= max_chars:
        return text
    return text[: max_chars - 3].rstrip() + "..."


def nullable_int(value: object) -> int | None:
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        return None
    try:
        return int(value)
    except (TypeError, ValueError):
        return None


def nullable_float(value: object) -> float | None:
    try:
        if pd.isna(value):
            return None
    except (TypeError, ValueError):
        return None
    try:
        return float(value)
    except (TypeError, ValueError):
        return None


def load_deepseek_topic_cache(path: Path) -> dict[str, dict]:
    if not path.exists():
        return {}
    try:
        payload = json.loads(path.read_text(encoding="utf-8"))
    except json.JSONDecodeError:
        return {}
    if not isinstance(payload, dict):
        return {}
    return {str(key): value for key, value in payload.items() if isinstance(value, dict)}


def save_deepseek_topic_cache(path: Path, cache: dict[str, dict]) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(json.dumps(cache, ensure_ascii=False, indent=2), encoding="utf-8")


def deepseek_payload_signature(payload: dict) -> str:
    encoded = json.dumps(
        {
            "schema_version": DEEPSEEK_TOPIC_SCHEMA_VERSION,
            "payload": payload,
        },
        ensure_ascii=False,
        sort_keys=True,
    ).encode("utf-8")
    return hashlib.sha1(encoded).hexdigest()[:16]


def string_list(value: object) -> list[str]:
    if isinstance(value, list):
        return [normalize_space(str(item)) for item in value if normalize_space(str(item))]
    text = normalize_space(safe_text(value))
    return [text] if text else []


def deepseek_bool(value: object, default: bool = True) -> bool:
    if isinstance(value, bool):
        return value
    text = normalize_space(safe_text(value)).lower()
    if not text:
        return default
    if text in {"true", "yes", "y", "1", "relevant", "related", "相关", "是"}:
        return True
    if text in {"false", "no", "n", "0", "not_relevant", "unrelated", "irrelevant", "不相关", "否"}:
        return False
    return default


def normalize_fusion_relevance(result: dict) -> tuple[bool, str, str]:
    raw_relevance = normalize_space(safe_text(result.get("fusion_relevance", ""))).lower()
    is_related = deepseek_bool(result.get("is_fusion_related", None), default=True)
    if raw_relevance in {"not_relevant", "unrelated", "irrelevant", "不相关"}:
        is_related = False
        relevance = "not_relevant"
    elif raw_relevance in {"uncertain", "unknown", "不确定"}:
        is_related = True
        relevance = "uncertain"
    elif raw_relevance in {"outlier"}:
        is_related = True
        relevance = "outlier"
    else:
        relevance = "relevant" if is_related else "not_relevant"

    reason = normalize_space(safe_text(result.get("fusion_relevance_reason", "")))
    if not reason:
        reason = "DeepSeek 未提供明确相关性理由，按保守规则保留该主题。" if is_related else "DeepSeek 判定该主题与核聚变不相关。"
    return is_related, relevance, reason


def outlier_topic_interpretation() -> dict:
    return {
        "route_name_cn": "离群专利集合",
        "route_name_en": "Outlier patent set",
        "topic_summary": "该集合为 HDBSCAN 识别的离群专利，不代表稳定的技术主题。",
        "topic_description": "这些专利没有形成足够紧密的语义簇，因此不宜被解释为明确技术路线。后续分析可以只将其作为噪声或待复核样本。",
        "technology_route_sentences": [
            "该集合缺少共同的技术对象、方法链条或应用目标，不能稳定归纳为单一技术路线。"
        ],
        "evidence_sentences": [
            "HDBSCAN 将这些文档标记为 -1，说明它们与其他主题中心的密度连接不足。"
        ],
        "fusion_industry_chain_position": "不适用",
        "fusion_industry_chain_relation": "该集合不代表稳定技术主题，因此不判定其在核聚变产业链中的位置。",
        "fusion_application_scenarios": [],
        "is_fusion_related": True,
        "fusion_relevance": "outlier",
        "fusion_relevance_reason": "该集合是聚类噪声集合，不作为独立技术主题做核聚变相关性剔除。",
        "confidence": "low",
        "status": "generated_outlier",
    }


def build_topic_evidence_payload(
    docs: pd.DataFrame,
    topic: int,
    topic_doc_indices: np.ndarray,
    representative_indices: np.ndarray,
) -> dict:
    group = docs.iloc[topic_doc_indices]
    years = pd.to_numeric(group["year"], errors="coerce") if "year" in group.columns else pd.Series(dtype=float)
    ipc_counter: Counter[str] = Counter()
    if "ipc_subclasses" in group.columns:
        for value in group["ipc_subclasses"].fillna("").astype(str):
            ipc_counter.update(code.strip() for code in value.split(";") if code.strip())

    def top_values(column: str, limit: int = 8) -> list[dict]:
        if column not in group.columns:
            return []
        values = group[column].fillna("").astype(str).map(normalize_space)
        counts = Counter(value for value in values if value)
        return [{"label": label, "count": int(count)} for label, count in counts.most_common(limit)]

    evidence_docs = []
    for doc_idx in representative_indices:
        row = docs.iloc[int(doc_idx)]
        evidence_docs.append(
            {
                "doc_id": safe_text(row.get("doc_id", "")),
                "title": compact_text(row.get("TI_raw", ""), 260),
                "abstract": compact_text(row.get("AB_raw", ""), 900),
                "representation_text": compact_text(row.get("TI_repr_text", ""), 700),
                "year": nullable_int(row.get("year", None)),
                "ipc_subclasses": safe_text(row.get("ipc_subclasses", "")),
                "citation_count": nullable_float(row.get("citation_count", None)),
            }
        )

    return {
        "topic_id": int(topic),
        "topic_size": int(len(topic_doc_indices)),
        "year_min": nullable_int(years.min()) if not years.dropna().empty else None,
        "year_max": nullable_int(years.max()) if not years.dropna().empty else None,
        "top_ipc_subclasses": [code for code, _ in ipc_counter.most_common(12)],
        "top_technology_labels": top_values("source_technology_label"),
        "top_route_labels": top_values("source_route_label"),
        "top_chain_level1": top_values("source_chain_level1"),
        "top_chain_level2": top_values("source_chain_level2"),
        "top_chain_level3": top_values("source_chain_level3"),
        "representative_docs": evidence_docs,
    }


def local_topic_interpretation(topic_payload: dict) -> dict:
    """Build a deterministic static interpretation from IncoPat labels and evidence."""

    def labels(key: str, limit: int = 3) -> list[str]:
        return [
            normalize_space(safe_text(item.get("label", "")))
            for item in topic_payload.get(key, [])[:limit]
            if normalize_space(safe_text(item.get("label", "")))
        ]

    routes = labels("top_route_labels", 3)
    technologies = labels("top_technology_labels", 3)
    level1 = [value for value in labels("top_chain_level1", 3) if value != "不适用"]
    level2 = [value for value in labels("top_chain_level2", 3) if value != "不适用"]
    level3 = [value for value in labels("top_chain_level3", 4) if value != "不适用"]
    documents = topic_payload.get("representative_docs", [])
    titles = [normalize_space(safe_text(item.get("title", ""))) for item in documents]
    titles = [title for title in titles if title][:3]

    replacement = {"确认无核聚变应用映射": "无直接聚变应用映射", "确认无关": "无直接聚变应用映射"}
    routes = [replacement.get(value, value) for value in routes]
    technologies = [replacement.get(value, value) for value in technologies]
    focus = (level3 or routes or technologies or level2 or ["聚变相关技术"])[0]
    route_name = focus if focus.endswith(("技术", "系统", "装置", "材料", "应用")) else f"{focus}技术"
    route_name = route_name[:18]
    route_context = "、".join(routes[:2]) or "聚变相关工程路线"
    objects = "、".join(level3[:3] or technologies[:3] or routes[:3])
    chain_position = "、".join(level1) if level1 else "跨环节支撑"
    chain_detail = "、".join(level2[:2]) if level2 else "聚变相关装置、部件与应用"

    summary = f"该主题集中于{focus}，主要覆盖{objects or route_context}等技术对象，并沿{route_context}方向形成专利布局。"
    description = (
        f"该主题由 IncoPat 简单专利族的标题、摘要、IPC 与技术标签共同归纳，核心内容聚焦{focus}。"
        f"相关专利主要落在{chain_position}的{chain_detail}，具体边界以代表专利披露的技术对象为准。"
    )
    route_sentences = [f"围绕{item}开展结构、材料、工艺或系统方案布局。" for item in (level3[:4] or routes[:4])]
    if not route_sentences:
        route_sentences = [f"围绕{focus}形成从基础方案到工程应用的技术演进。"]
    evidence_sentences = [f"代表专利“{title}”体现了该主题的主要技术指向。" for title in titles]
    if not evidence_sentences:
        evidence_sentences = ["主题判断依据为聚类专利的标题、摘要、IPC 与 IncoPat 技术标签。"]
    scenarios = [f"可用于{item}相关的聚变工程研发与系统集成。" for item in (level3[:3] or level2[:3] or [focus])]
    return {
        "route_name_cn": route_name,
        "route_name_en": "IncoPat classified technology topic",
        "topic_summary": summary,
        "topic_description": description,
        "technology_route_sentences": route_sentences,
        "evidence_sentences": evidence_sentences,
        "fusion_industry_chain_position": chain_position,
        "fusion_industry_chain_relation": f"该技术通过{chain_detail}进入核聚变产业链，主要服务于{objects or focus}相关研发与工程活动。",
        "fusion_application_scenarios": scenarios,
        "is_fusion_related": True,
        "fusion_relevance": "relevant",
        "fusion_relevance_reason": "按已确认口径，全部 IncoPat 简单专利族均纳入聚变相关技术分析范围。",
        "confidence": "medium",
        "status": "generated_local",
        "model": "IncoPat标签规则与本地主题归纳",
        "generated_at": int(time.time()),
    }


def build_deepseek_topic_prompt(topic_payload: dict) -> str:
    return (
        "你是核聚变专利技术路线分析专家。下面是一组已经由 PatentBERT/UMAP/HDBSCAN "
        "聚到同一 topic 的代表专利证据。\n\n"
        "请直接提炼该 topic 的技术主题，不要输出孤立关键词、逗号堆砌词组"
        "或单个名词。所有解释性字段必须写成完整句子，重点说明"
        "技术对象、关键方法、解决的问题和应用目标。\n\n"
        "必须只返回 JSON 对象，字段如下：\n"
        "{\n"
        '  "route_name_cn": "中文技术路线短标题，不超过 18 个字",\n'
        '  "route_name_en": "English route title",\n'
        '  "topic_summary": "一句完整中文主题句，30-90 字，说明该 topic 主要围绕什么技术方向",\n'
        '  "topic_description": "2-3 个完整中文句子，概括该主题的技术内涵和边界",\n'
        '  "technology_route_sentences": ["3-5 个完整中文句子，每句描述一个技术路线环节"],\n'
        '  "evidence_sentences": ["2-4 个完整中文句子，说明代表专利中反复出现的证据"],\n'
        '  "fusion_industry_chain_position": "说明其位于核聚变产业链的上游材料与部件、中游装置与系统、下游运行与应用或跨环节支撑；可写多个环节",\n'
        '  "fusion_industry_chain_relation": "1-3 个完整中文句子，说明该技术如何进入核聚变产业链、服务哪些聚变系统或解决什么工程问题",\n'
        '  "fusion_application_scenarios": ["2-5 个完整中文句子，说明在核聚变装置、部件、建设、运行或维护中的具体应用"],\n'
        '  "is_fusion_related": true,\n'
        '  "fusion_relevance": "relevant|not_relevant|uncertain",\n'
        '  "fusion_relevance_reason": "一个完整中文句子，说明为什么该 topic 与核聚变相关或不相关",\n'
        '  "confidence": "high|medium|low"\n'
        "}\n\n"
        "约束：\n"
        "1. 不要编造代表专利中没有支持的技术效果。\n"
        "2. 主题证据不足时，confidence 设为 low，并在 topic_description 中说明不确定性。\n"
        "3. topic_summary 必须是句子，不要写成关键词列表。\n"
        "4. 必须判断该 topic 是否与核聚变技术相关。与聚变堆、等离子体约束、磁体、真空室、偏滤器、"
        "包层、燃料循环、氚处理、冷却、诊断、遥操作、装配维护、聚变材料、聚变电站系统等直接或支撑性方向相关，"
        "均应视为相关。\n"
        "5. 只有当代表专利明确主要服务于非核聚变场景，且缺少聚变应用或支撑关系时，"
        "才将 is_fusion_related 设为 false 且 fusion_relevance 设为 not_relevant。没有明确把握时，"
        "必须保留，设为 is_fusion_related=true 且 fusion_relevance=uncertain。\n"
        "6. 产业链关系和应用必须以代表专利证据为依据。若属于通用支撑技术，应明确写出其可能服务的"
        "聚变系统以及成立条件；若证据不足，不得编造，必须直接说明关系尚不明确。\n\n"
        f"主题证据：\n{json.dumps(topic_payload, ensure_ascii=False, indent=2)}"
    )


def parse_deepseek_json_content(content: str) -> dict:
    text = content.strip()
    if text.startswith("```"):
        text = re.sub(r"^```(?:json)?\s*", "", text, flags=re.IGNORECASE)
        text = re.sub(r"\s*```$", "", text).strip()
    try:
        result = json.loads(text)
    except json.JSONDecodeError as exc:
        excerpt = text[:1200]
        raise RuntimeError(
            "DeepSeek returned invalid JSON. This is usually a truncated or malformed model response. "
            f"JSON error: {exc}. Response excerpt: {excerpt!r}"
        ) from exc
    if not isinstance(result, dict):
        raise RuntimeError("DeepSeek returned a non-object JSON payload.")
    return result


def call_deepseek_topic_sentence(
    prompt: str,
    api_key: str,
    model: str,
    base_url: str,
    timeout: int,
    retries: int,
) -> dict:
    url = base_url.rstrip("/") + "/chat/completions"
    last_error: Exception | None = None
    for attempt in range(max(1, retries + 1)):
        retry_note = ""
        if attempt:
            retry_note = (
                "\n\n上一次请求失败或响应不是合法 JSON。请重新输出一个完整 JSON 对象，"
                "不要包含 Markdown，不要在字符串中使用未转义换行，不要省略任何结尾括号。"
            )
        body = {
            "model": model,
            "messages": [
                {
                    "role": "system",
                    "content": (
                        "你是核聚变专利主题提炼专家。必须输出有效 JSON；"
                        "主题表达必须是完整句子，不要输出孤立关键词列表。"
                    ),
                },
                {"role": "user", "content": prompt + retry_note},
            ],
            "response_format": {"type": "json_object"},
            "temperature": 0.05,
            "max_tokens": 2400,
        }
        request = urllib.request.Request(
            url=url,
            data=json.dumps(body, ensure_ascii=False).encode("utf-8"),
            headers={
                "Authorization": f"Bearer {api_key}",
                "Content-Type": "application/json",
            },
            method="POST",
        )
        try:
            with urllib.request.urlopen(request, timeout=timeout) as response:
                payload = json.loads(response.read().decode("utf-8"))
        except urllib.error.HTTPError as exc:
            detail = exc.read().decode("utf-8", errors="ignore")
            last_error = RuntimeError(f"DeepSeek API HTTP {exc.code}: {detail}")
            if exc.code in {408, 409, 425, 429, 500, 502, 503, 504} and attempt < retries:
                time.sleep(min(3.0 * (attempt + 1), 15.0))
                continue
            raise last_error from exc
        except urllib.error.URLError as exc:
            last_error = RuntimeError(f"DeepSeek API connection failed: {exc}")
            if attempt < retries:
                time.sleep(min(3.0 * (attempt + 1), 15.0))
                continue
            raise last_error from exc
        except http.client.IncompleteRead as exc:
            last_error = RuntimeError(f"DeepSeek API response was interrupted: {exc}")
            if attempt < retries:
                time.sleep(min(3.0 * (attempt + 1), 15.0))
                continue
            raise last_error from exc
        except TimeoutError as exc:
            last_error = RuntimeError(f"DeepSeek API request timed out: {exc}")
            if attempt < retries:
                time.sleep(min(3.0 * (attempt + 1), 15.0))
                continue
            raise last_error from exc

        content = payload["choices"][0]["message"]["content"]
        try:
            result = parse_deepseek_json_content(content)
            break
        except RuntimeError as exc:
            last_error = exc
            if attempt < retries:
                time.sleep(min(2.0 * (attempt + 1), 6.0))
                continue
            raise
    else:
        raise RuntimeError(f"DeepSeek JSON parsing failed: {last_error}") from last_error

    result["status"] = "generated"
    result["model"] = model
    result["generated_at"] = int(time.time())
    return result


def normalize_deepseek_topic_result(result: dict, topic: int, topic_size: int, is_outlier: bool, cache_key: str) -> dict:
    route_name_cn = normalize_space(safe_text(result.get("route_name_cn", "")))
    route_name_en = normalize_space(safe_text(result.get("route_name_en", "")))
    topic_summary = normalize_space(safe_text(result.get("topic_summary", "")))
    topic_description = normalize_space(safe_text(result.get("topic_description", "")))
    route_sentences = string_list(result.get("technology_route_sentences", []))
    evidence_sentences = string_list(result.get("evidence_sentences", []))
    fusion_industry_chain_position = normalize_space(
        safe_text(result.get("fusion_industry_chain_position", ""))
    )
    fusion_industry_chain_relation = normalize_space(
        safe_text(result.get("fusion_industry_chain_relation", ""))
    )
    fusion_application_scenarios = string_list(result.get("fusion_application_scenarios", []))
    if not fusion_industry_chain_position:
        fusion_industry_chain_position = "关系尚不明确"
    if not fusion_industry_chain_relation:
        fusion_industry_chain_relation = "代表专利证据不足，暂不能确定该技术与核聚变产业链的具体关系。"
    if not fusion_application_scenarios:
        fusion_application_scenarios = ["代表专利证据不足，具体核聚变应用场景仍需进一步验证。"]
    is_fusion_related, fusion_relevance, fusion_relevance_reason = normalize_fusion_relevance(result)

    if not topic_summary:
        if topic_description:
            topic_summary = topic_description.split("。", 1)[0].strip() + "。"
        elif route_sentences:
            topic_summary = route_sentences[0]
        else:
            topic_summary = "该主题需要结合代表专利进一步人工复核。"

    return {
        "topic_id": int(topic),
        "topic_size": int(topic_size),
        "is_bertopic_outlier": bool(is_outlier),
        "topic_keywords": topic_summary,
        "route_name_cn": route_name_cn,
        "route_name_en": route_name_en,
        "topic_summary": topic_summary,
        "topic_description": topic_description,
        "technology_route_sentences": " || ".join(route_sentences),
        "evidence_sentences": " || ".join(evidence_sentences),
        "fusion_industry_chain_position": fusion_industry_chain_position,
        "fusion_industry_chain_relation": fusion_industry_chain_relation,
        "fusion_application_scenarios": " || ".join(fusion_application_scenarios),
        "is_fusion_related": bool(is_fusion_related),
        "fusion_relevance": fusion_relevance,
        "fusion_relevance_reason": fusion_relevance_reason,
        "confidence": normalize_space(safe_text(result.get("confidence", "unknown"))) or "unknown",
        "deepseek_status": normalize_space(safe_text(result.get("status", "unknown"))),
        "deepseek_model": normalize_space(safe_text(result.get("model", ""))),
        "deepseek_cache_key": cache_key,
    }


def compute_deepseek_topic_sentences(
    docs: pd.DataFrame,
    embeddings: np.ndarray,
    topic_index: pd.DataFrame,
    topic_embeddings: np.ndarray,
    args: argparse.Namespace,
) -> pd.DataFrame:
    require_sklearn()
    topic_ids = docs["topic_id"].astype(int).to_numpy()
    doc_embeddings = normalize(np.asarray(embeddings, dtype=np.float64), norm="l2", axis=1)
    cache_path = data_path(args.deepseek_topic_cache)
    cache = load_deepseek_topic_cache(cache_path)
    api_key = os.environ.get(args.deepseek_api_key_env, "").strip()
    rows_by_topic: dict[int, dict] = {}
    pending = []
    ordered_topics = topic_index["topic_id"].astype(int).to_numpy().tolist()

    for pos, topic_value in enumerate(topic_index["topic_id"].astype(int).to_numpy()):
        topic = int(topic_value)
        topic_doc_indices = np.where(topic_ids == topic)[0]
        topic_size = int(len(topic_doc_indices))
        cache_key = f"topic_{topic}_outlier" if topic == -1 else ""

        if topic == -1:
            result = outlier_topic_interpretation()
            rows_by_topic[topic] = normalize_deepseek_topic_result(result, topic, topic_size, True, cache_key)
            continue

        similarities = doc_embeddings[topic_doc_indices] @ topic_embeddings[pos]
        representative_count = min(max(1, int(args.deepseek_topic_docs)), topic_size)
        representative_indices = topic_doc_indices[np.argsort(-similarities)[:representative_count]]
        topic_payload = build_topic_evidence_payload(
            docs=docs,
            topic=topic,
            topic_doc_indices=topic_doc_indices,
            representative_indices=representative_indices,
        )
        signature = deepseek_payload_signature(
            {
                "model": args.deepseek_model,
                "topic": topic_payload,
            }
        )
        cache_key = f"topic_{topic}_{signature}"
        cached = cache.get(cache_key)
        if cached and not args.refresh_deepseek_topics and cached.get("status") in {"generated", "generated_local"}:
            print(f"Topic {topic}: using cached summary.")
            rows_by_topic[topic] = normalize_deepseek_topic_result(cached, topic, topic_size, False, cache_key)
        elif args.local_topic_summaries:
            result = local_topic_interpretation(topic_payload)
            cache[cache_key] = result
            rows_by_topic[topic] = normalize_deepseek_topic_result(result, topic, topic_size, False, cache_key)
            save_deepseek_topic_cache(cache_path, cache)
            print(f"Topic {topic}: generated locally from IncoPat labels.")
        else:
            if not api_key:
                raise RuntimeError(
                    f"DeepSeek topic extraction is required, but environment variable "
                    f"{args.deepseek_api_key_env} is not set and no valid cache exists for topic {topic}. "
                    f"Set {args.deepseek_api_key_env} or provide {cache_path}."
                )
            prompt = build_deepseek_topic_prompt(topic_payload)
            pending.append({
                "topic": topic,
                "topic_size": topic_size,
                "cache_key": cache_key,
                "representative_count": representative_count,
                "prompt": build_deepseek_topic_prompt(topic_payload),
            })

    def generate(task: dict) -> tuple[dict, dict]:
        topic = task["topic"]
        print(
            f"DeepSeek topic {topic}: generating summary from "
            f"{task['representative_count']} representative docs..."
        )
        result = call_deepseek_topic_sentence(
            prompt=task["prompt"],
            api_key=api_key,
            model=args.deepseek_model,
            base_url=args.deepseek_base_url,
            timeout=int(args.deepseek_timeout),
            retries=int(args.deepseek_retries),
        )
        return task, result

    failures = []
    if pending:
        workers = max(1, min(int(args.deepseek_workers), len(pending)))
        print(f"DeepSeek topic generation: {len(pending)} pending, {workers} workers.")
        with ThreadPoolExecutor(max_workers=workers) as executor:
            future_tasks = {executor.submit(generate, task): task for task in pending}
            for future in as_completed(future_tasks):
                task = future_tasks[future]
                topic = task["topic"]
                cache_key = task["cache_key"]
                try:
                    _, result = future.result()
                except Exception as exc:
                    cache[cache_key] = {
                        "status": "failed",
                        "error": str(exc),
                        "model": args.deepseek_model,
                        "generated_at": int(time.time()),
                    }
                    failures.append((topic, exc))
                else:
                    cache[cache_key] = result
                    rows_by_topic[topic] = normalize_deepseek_topic_result(
                        result, topic, task["topic_size"], False, cache_key
                    )
                    print(f"DeepSeek topic {topic}: completed.")
                save_deepseek_topic_cache(cache_path, cache)

    if failures:
        topics = ", ".join(str(topic) for topic, _ in failures[:12])
        raise RuntimeError(f"DeepSeek topic extraction failed for {len(failures)} topics: {topics}") from failures[0][1]

    rows = [rows_by_topic[int(topic)] for topic in ordered_topics]
    save_deepseek_topic_cache(cache_path, cache)
    return pd.DataFrame(rows)


def relabel_non_fusion_topics_as_noise(docs: pd.DataFrame, topic_keywords: pd.DataFrame) -> dict[str, int]:
    docs["is_deepseek_non_fusion_noise"] = False
    docs["deepseek_fusion_relevance"] = ""
    docs["deepseek_fusion_relevance_reason"] = ""
    docs["topic_id_before_deepseek_filter"] = docs["topic_id"].astype(int)
    docs["deepseek_non_fusion_topic_id"] = ""

    if topic_keywords.empty or "topic_id" not in topic_keywords.columns:
        stats = {
            "deepseek_non_fusion_topic_count": 0,
            "deepseek_non_fusion_doc_count": 0,
            "topic_count_excluding_minus_1_after_deepseek_filter": int(docs.loc[docs["topic_id"].ne(-1), "topic_id"].nunique()),
            "topic_count_including_minus_1_after_deepseek_filter": int(docs["topic_id"].nunique()),
            "noise_doc_count_after_deepseek_filter": int(docs["topic_id"].eq(-1).sum()),
        }
        docs.attrs["deepseek_relevance_filter_stats"] = stats
        return stats

    relevance_map = {
        int(row["topic_id"]): normalize_space(safe_text(row.get("fusion_relevance", "")))
        for _, row in topic_keywords.iterrows()
        if pd.notna(row.get("topic_id", np.nan))
    }
    reason_map = {
        int(row["topic_id"]): normalize_space(safe_text(row.get("fusion_relevance_reason", "")))
        for _, row in topic_keywords.iterrows()
        if pd.notna(row.get("topic_id", np.nan))
    }
    related_map = {
        int(row["topic_id"]): deepseek_bool(row.get("is_fusion_related", True), default=True)
        for _, row in topic_keywords.iterrows()
        if pd.notna(row.get("topic_id", np.nan))
    }

    docs["deepseek_fusion_relevance"] = docs["topic_id"].astype(int).map(relevance_map).fillna("")
    docs["deepseek_fusion_relevance_reason"] = docs["topic_id"].astype(int).map(reason_map).fillna("")

    non_fusion_topics = sorted(
        topic
        for topic, is_related in related_map.items()
        if topic != -1 and not is_related
    )
    non_fusion_mask = docs["topic_id"].isin(non_fusion_topics)
    docs["is_deepseek_non_fusion_noise"] = non_fusion_mask
    if non_fusion_topics:
        docs.loc[non_fusion_mask, "deepseek_non_fusion_topic_id"] = docs.loc[non_fusion_mask, "topic_id"].astype(int).astype(str)
        docs.loc[non_fusion_mask, "topic_id"] = -1
        docs.loc[non_fusion_mask, "topic_probability"] = 0.0
        docs["is_bertopic_outlier"] = docs["topic_id"].eq(-1)

    stats = {
        "deepseek_non_fusion_topic_count": int(len(non_fusion_topics)),
        "deepseek_non_fusion_doc_count": int(non_fusion_mask.sum()),
        "topic_count_excluding_minus_1_after_deepseek_filter": int(docs.loc[docs["topic_id"].ne(-1), "topic_id"].nunique()),
        "topic_count_including_minus_1_after_deepseek_filter": int(docs["topic_id"].nunique()),
        "noise_doc_count_after_deepseek_filter": int(docs["topic_id"].eq(-1).sum()),
    }
    docs.attrs["deepseek_relevance_filter_stats"] = stats
    return stats


def fit_trend_for_topic(
    topic: int,
    year_counts: pd.DataFrame,
    fitting_years: np.ndarray,
    min_points: int,
) -> tuple[float, float, float, str]:
    subset = year_counts[
        (year_counts["topic_id"] == topic) & (year_counts["year"].isin(fitting_years))
    ].sort_values("year")
    subset = subset[subset["total_year_count"] > 0].copy()
    if len(subset) < min_points:
        return (np.nan, np.nan, np.nan, "insufficient_year_points")

    y = subset["topic_year_count"].astype(float).to_numpy()
    total = subset["total_year_count"].astype(float).to_numpy()
    x = subset["year"].astype(float).to_numpy()
    x_scaled = x - np.min(x)

    try:
        import statsmodels.api as sm

        design = sm.add_constant(x_scaled, has_constant="add")
        with warnings.catch_warnings():
            warnings.simplefilter("ignore")
            model = sm.GLM(
                y,
                design,
                family=sm.families.NegativeBinomial(),
                offset=np.log(total),
            )
            result = model.fit(maxiter=200, disp=0)
        beta = float(result.params[1])
        if np.isfinite(beta):
            growth = float(math.exp(beta) - 1.0)
            return (growth, beta, growth, "negative_binomial_glm")
    except Exception:
        pass

    share = (y + 0.5) / (total + 1.0)
    if len(np.unique(x_scaled)) < 2:
        return (np.nan, np.nan, np.nan, "fallback_failed")
    slope = float(np.polyfit(x_scaled, np.log(share), 1)[0])
    growth = float(math.exp(slope) - 1.0)
    return (growth, slope, growth, "fallback_log_share_slope")


def build_year_counts(docs: pd.DataFrame) -> pd.DataFrame:
    valid = docs.dropna(subset=["year", "topic_id"]).copy()
    if valid.empty:
        return pd.DataFrame(
            columns=["topic_id", "year", "topic_year_count", "total_year_count", "topic_year_share"]
        )
    valid["year"] = valid["year"].astype(int)
    years = np.arange(valid["year"].min(), valid["year"].max() + 1, dtype=int)
    topics = np.array(sorted(valid["topic_id"].astype(int).unique()), dtype=int)
    total_counts = valid.groupby("year").size().reindex(years, fill_value=0)
    topic_counts = valid.groupby(["topic_id", "year"]).size()

    rows = []
    for topic in topics:
        for year in years:
            topic_count = int(topic_counts.get((topic, year), 0))
            total_count = int(total_counts.loc[year])
            rows.append(
                {
                    "topic_id": int(topic),
                    "year": int(year),
                    "topic_year_count": topic_count,
                    "total_year_count": total_count,
                    "topic_year_share": topic_count / total_count if total_count else np.nan,
                }
            )
    return pd.DataFrame(rows)


def compute_indicator_tables(
    docs: pd.DataFrame,
    embeddings: np.ndarray,
    recent_window: int,
    min_year_points: int,
    args: argparse.Namespace,
) -> tuple[pd.DataFrame, pd.DataFrame, pd.DataFrame, pd.DataFrame]:
    topic_index, topic_embeddings = compute_topic_embeddings(embeddings, docs["topic_id"].astype(int).to_numpy())
    topic_keywords = compute_deepseek_topic_sentences(docs, embeddings, topic_index, topic_embeddings, args)
    relevance_stats = (
        keep_all_topics_in_scope(docs)
        if args.all_topics_related
        else relabel_non_fusion_topics_as_noise(docs, topic_keywords)
    )
    if relevance_stats["deepseek_non_fusion_topic_count"]:
        print(
            "Relabelled DeepSeek non-fusion topics as noise: "
            f"{relevance_stats['deepseek_non_fusion_topic_count']} topics, "
            f"{relevance_stats['deepseek_non_fusion_doc_count']} patent families."
        )
        topic_index, topic_embeddings = compute_topic_embeddings(embeddings, docs["topic_id"].astype(int).to_numpy())
        topic_keywords = compute_deepseek_topic_sentences(docs, embeddings, topic_index, topic_embeddings, args)
    representatives = compute_representative_docs(docs, embeddings, topic_index, topic_embeddings)
    topic_keywords["representative_docs"] = topic_keywords["topic_id"].map(representatives).fillna("")

    raw = topic_keywords.copy()
    citation = docs.groupby("topic_id")["citation_count"]
    raw = raw.merge(
        citation.mean().rename("impact_mean_citation_raw").reset_index(),
        on="topic_id",
        how="left",
    )
    log_citation = docs.assign(_log_citation=np.log1p(pd.to_numeric(docs["citation_count"], errors="coerce")))
    raw = raw.merge(
        log_citation.groupby("topic_id")["_log_citation"]
        .mean()
        .rename("impact_log_mean_citation_raw")
        .reset_index(),
        on="topic_id",
        how="left",
    )
    raw["impact_raw"] = raw["impact_log_mean_citation_raw"]

    years = docs.groupby("topic_id")["year"].agg(["mean", "median", "min", "max"]).reset_index()
    years.columns = ["topic_id", "year_mean", "year_median", "year_min", "year_max"]
    raw = raw.merge(years, on="topic_id", how="left")
    raw["novelty_raw"] = raw["year_mean"]

    year_counts = build_year_counts(docs)
    if not year_counts.empty:
        observed_years = (
            year_counts.loc[year_counts["total_year_count"] > 0, "year"]
            .drop_duplicates()
            .sort_values()
            .to_numpy(dtype=int)
        )
    else:
        observed_years = np.array([], dtype=int)

    trend_rows = []
    for topic in raw["topic_id"].astype(int):
        if len(observed_years) == 0:
            short = (np.nan, np.nan, np.nan, "missing_year")
            long = (np.nan, np.nan, np.nan, "missing_year")
        else:
            recent_start = int(observed_years.max() - recent_window + 1)
            short_years = observed_years[observed_years >= recent_start]
            short = fit_trend_for_topic(topic, year_counts, short_years, min_year_points)
            long = fit_trend_for_topic(topic, year_counts, observed_years, min_year_points)
        trend_rows.append(
            {
                "topic_id": topic,
                "short_trend_raw": short[0],
                "short_trend_beta_raw": short[1],
                "short_trend_growth_raw": short[2],
                "short_trend_method": short[3],
                "long_trend_raw": long[0],
                "long_trend_beta_raw": long[1],
                "long_trend_growth_raw": long[2],
                "long_trend_method": long[3],
            }
        )
    raw = raw.merge(pd.DataFrame(trend_rows), on="topic_id", how="left")

    if len(topic_embeddings) >= 2:
        similarity = topic_embeddings @ topic_embeddings.T
        centrality = (similarity.sum(axis=1) - 1.0) / (len(topic_embeddings) - 1)
    else:
        centrality = np.full(len(topic_embeddings), np.nan)
    centrality_df = topic_index.copy()
    centrality_df["centrality_raw"] = centrality
    raw = raw.merge(centrality_df, on="topic_id", how="left")

    cross_domain = compute_cross_domain(docs)
    raw = raw.merge(cross_domain, on="topic_id", how="left")

    lof_df = topic_index.copy()
    if len(topic_embeddings) >= 3:
        k = min(10, len(topic_embeddings) - 1)
        lof = LocalOutlierFactor(n_neighbors=k, metric="cosine")
        lof.fit_predict(topic_embeddings)
        lof_df["lof_raw"] = -lof.negative_outlier_factor_
    else:
        lof_df["lof_raw"] = np.nan
    raw = raw.merge(lof_df, on="topic_id", how="left")

    raw = raw[
        [
            "topic_id",
            "topic_size",
            "is_bertopic_outlier",
            "topic_keywords",
            "route_name_cn",
            "route_name_en",
            "topic_summary",
            "topic_description",
            "technology_route_sentences",
            "evidence_sentences",
            "fusion_industry_chain_position",
            "fusion_industry_chain_relation",
            "fusion_application_scenarios",
            "is_fusion_related",
            "fusion_relevance",
            "fusion_relevance_reason",
            "confidence",
            "deepseek_status",
            "deepseek_model",
            "deepseek_cache_key",
            "representative_docs",
            "impact_raw",
            "impact_mean_citation_raw",
            "impact_log_mean_citation_raw",
            "novelty_raw",
            "year_mean",
            "year_median",
            "year_min",
            "year_max",
            "short_trend_raw",
            "short_trend_beta_raw",
            "short_trend_growth_raw",
            "short_trend_method",
            "long_trend_raw",
            "long_trend_beta_raw",
            "long_trend_growth_raw",
            "long_trend_method",
            "centrality_raw",
            "cross_domain_raw",
            "ipc_entropy_raw",
            "ipc_subclass_count",
            "ipc_subclasses",
            "lof_raw",
        ]
    ].sort_values("topic_id")

    normalized = normalize_indicator_table(raw)
    topic_embedding_df = pd.DataFrame(topic_embeddings, columns=[f"emb_{i:03d}" for i in range(topic_embeddings.shape[1])])
    topic_embedding_df.insert(0, "topic_id", topic_index["topic_id"].astype(int).to_numpy())
    return raw, normalized, year_counts, topic_embedding_df


def keep_all_topics_in_scope(docs: pd.DataFrame) -> dict[str, int]:
    """Retain all IncoPat families under the confirmed all-related rule."""
    docs["is_deepseek_non_fusion_noise"] = False
    docs["deepseek_fusion_relevance"] = ""
    docs["deepseek_fusion_relevance_reason"] = ""
    docs["topic_id_before_deepseek_filter"] = docs["topic_id"].astype(int)
    docs["deepseek_non_fusion_topic_id"] = ""
    stats = {
        "deepseek_non_fusion_topic_count": 0,
        "deepseek_non_fusion_doc_count": 0,
        "topic_count_excluding_minus_1_after_deepseek_filter": int(docs.loc[docs["topic_id"].ne(-1), "topic_id"].nunique()),
        "topic_count_including_minus_1_after_deepseek_filter": int(docs["topic_id"].nunique()),
        "noise_doc_count_after_deepseek_filter": int(docs["topic_id"].eq(-1).sum()),
    }
    docs.attrs["deepseek_relevance_filter_stats"] = stats
    return stats


def compute_cross_domain(docs: pd.DataFrame) -> pd.DataFrame:
    all_codes = [code for codes in docs["_ipc_list"] for code in codes]
    global_codes = sorted(set(all_codes))
    global_denominator = math.log(len(global_codes)) if len(global_codes) > 1 else np.nan

    rows = []
    for topic, group in docs.groupby("topic_id", sort=True):
        counter: Counter[str] = Counter()
        for codes in group["_ipc_list"]:
            counter.update(codes)
        total = sum(counter.values())
        if total == 0 or not np.isfinite(global_denominator):
            entropy = np.nan
            diversity = np.nan
        else:
            probs = np.asarray([count / total for count in counter.values()], dtype=float)
            entropy = float(-(probs * np.log(probs)).sum())
            diversity = float(entropy / global_denominator)
        rows.append(
            {
                "topic_id": int(topic),
                "cross_domain_raw": diversity,
                "ipc_entropy_raw": entropy,
                "ipc_subclass_count": int(len(counter)),
                "ipc_subclasses": "; ".join(code for code, _ in counter.most_common()),
            }
        )
    return pd.DataFrame(rows)


def percentile_score(values: pd.Series, winsorize: bool = True) -> pd.Series:
    raw = pd.to_numeric(values, errors="coerce")
    out = pd.Series(np.nan, index=values.index, dtype=float)
    valid = raw.dropna()
    if valid.empty:
        return out
    working = valid.copy()
    if winsorize and len(working) > 2:
        lower = working.quantile(0.01)
        upper = working.quantile(0.99)
        working = working.clip(lower=lower, upper=upper)
    if working.nunique(dropna=True) == 1:
        out.loc[working.index] = 0.5
        return out
    ranks = working.rank(method="average", ascending=True)
    out.loc[working.index] = (ranks - 1.0) / (len(working) - 1.0)
    return out


def normalize_indicator_table(raw: pd.DataFrame) -> pd.DataFrame:
    mapping = {
        "impact_raw": "impact_score",
        "novelty_raw": "novelty_score",
        "short_trend_raw": "short_trend_score",
        "long_trend_raw": "long_trend_score",
        "centrality_raw": "centrality_score",
        "cross_domain_raw": "cross_domain_score",
        "lof_raw": "lof_score",
    }
    normalized = raw[["topic_id", "topic_size", "is_bertopic_outlier", "topic_keywords"]].copy()
    for col in [
        "route_name_cn",
        "route_name_en",
        "topic_summary",
        "topic_description",
        "technology_route_sentences",
        "evidence_sentences",
        "fusion_industry_chain_position",
        "fusion_industry_chain_relation",
        "fusion_application_scenarios",
        "is_fusion_related",
        "fusion_relevance",
        "fusion_relevance_reason",
        "confidence",
        "deepseek_status",
        "deepseek_model",
        "deepseek_cache_key",
    ]:
        if col in raw.columns:
            normalized[col] = raw[col]
    for raw_col, score_col in mapping.items():
        normalized[score_col] = percentile_score(raw[raw_col], winsorize=True)
    return normalized


def output_path_for_new_file(path: Path) -> Path:
    if not path.exists():
        return path
    stem = path.stem
    suffix = path.suffix
    parent = path.parent
    index = 2
    while True:
        candidate = parent / f"{stem}_{index}{suffix}"
        if not candidate.exists():
            return candidate
        index += 1


def write_workbook(
    output_path: Path,
    docs: pd.DataFrame,
    topic_keywords: pd.DataFrame,
    year_counts: pd.DataFrame,
    raw: pd.DataFrame,
    normalized: pd.DataFrame,
    topic_embeddings: pd.DataFrame,
    run_log: pd.DataFrame,
) -> None:
    preprocessed_cols = [
        "doc_id",
        "source_family_id",
        "source_representative_lens_id",
        "source_lens_id",
        "source_display_key",
        "source_jurisdiction",
        "source_document_type",
        "source_legal_status",
        "source_publication_date",
        "TI_raw",
        "TI_clean",
        "TI_norm",
        "TI_embed_text",
        "AB_raw",
        "AB_clean",
        "AB_norm",
        "AB_embed_text",
        "patentbert_text",
        "TI_repr_text",
        "year",
        "citation_count",
        "ipc_raw",
        "ipc_subclasses",
    ]
    doc_topic_cols = [
        "doc_id",
        "source_family_id",
        "source_representative_lens_id",
        "source_lens_id",
        "source_display_key",
        "source_jurisdiction",
        "source_document_type",
        "source_legal_status",
        "source_publication_date",
        "topic_id",
        "topic_id_raw",
        "topic_id_before_deepseek_filter",
        "is_bertopic_outlier",
        "is_small_topic_noise",
        "is_deepseek_non_fusion_noise",
        "deepseek_non_fusion_topic_id",
        "deepseek_fusion_relevance",
        "deepseek_fusion_relevance_reason",
        "raw_topic_size",
        "TI_raw",
        "TI_embed_text",
        "AB_raw",
        "AB_embed_text",
        "patentbert_text",
        "TI_repr_text",
        "year",
        "citation_count",
        "ipc_raw",
        "ipc_subclasses",
        "topic_probability",
    ]
    preprocessed = docs[[col for col in preprocessed_cols if col in docs.columns]].copy()
    doc_topics = docs[[col for col in doc_topic_cols if col in docs.columns]].copy()

    with pd.ExcelWriter(output_path, engine="openpyxl") as writer:
        preprocessed.to_excel(writer, sheet_name="01_preprocessed_docs", index=False)
        doc_topics.to_excel(writer, sheet_name="02_doc_topics", index=False)
        topic_keywords.to_excel(writer, sheet_name="03_topic_keywords", index=False)
        year_counts.to_excel(writer, sheet_name="04_topic_year_counts", index=False)
        raw.to_excel(writer, sheet_name="05_indicator_raw", index=False)
        normalized.to_excel(writer, sheet_name="06_indicator_norm", index=False)
        topic_embeddings.to_excel(writer, sheet_name="topic_embeddings", index=False)
        run_log.to_excel(writer, sheet_name="run_log", index=False)


SPELLING_CORRECTIONS = {
    "tokomak": "tokamak",
    "tokmak": "tokamak",
    "tokakk": "tokamak",
    "tokka": "tokamak",
    "tokmac": "tokamak",
    "tokak mark": "tokamak",
    "toka mak": "tokamak",
    "diverter": "divertor",
    "tearing mold": "tearing mode",
    "tearing mould": "tearing mode",
    "boundary local model": "edge localized mode",
    "edge local mode": "edge localized mode",
    "ultra conducting": "superconducting",
    "superconductive": "superconducting",
    "inertia constraint nuclear fusion": "inertial confinement fusion",
    "inertia limitation fusion": "inertial confinement fusion",
}


ABBREVIATIONS = {
    "hts": "hts high temperature superconducting",
    "icf": "icf inertial confinement fusion",
    "nbi": "nbi neutral beam injection",
    "nnbi": "nnbi negative neutral beam injection",
    "elm": "elm edge localized mode",
    "frc": "frc field reversed configuration",
    "iec": "iec inertial electrostatic confinement",
    "lenr": "lenr low energy nuclear reaction",
}


TERM_NORMALIZATION = {
    "tritium proliferation": "tritium breeding",
    "tritium increment": "tritium breeding",
    "tritium increasing": "tritium breeding",
    "tritium multiplying": "tritium breeding",
    "tritium generating": "tritium breeding",
    "black cavity": "hohlraum",
    "target pill": "target pellet",
    "fuel capsule": "target pellet",
    "freezing target": "cryogenic target",
    "frozen target": "cryogenic target",
    "plasma oriented material": "plasma facing material",
    "plasma oriented component": "plasma facing component",
    "liquid lithium lead": "lithium lead",
    "low activated steel": "reduced activation steel",
    "low activation steel": "reduced activation steel",
}


FUSION_CONTEXT_WORDS = {
    "fusion",
    "tokamak",
    "plasma",
    "reactor",
    "tritium",
    "lithium",
    "tungsten",
    "target plate",
    "first wall",
    "blanket",
    "vacuum chamber",
}


BREEDING_CONTEXT_WORDS = {
    "tritium",
    "breeding",
    "lithium",
    "lithium lead",
    "fusion reactor",
    "blanket",
    "helium coolant",
}


PHRASES_TO_PROTECT = [
    "magnetic confinement fusion",
    "inertial confinement fusion",
    "field reversed configuration",
    "neutral beam injection",
    "high temperature superconducting",
    "toroidal field coil",
    "poloidal field coil",
    "tritium breeding blanket",
    "tritium breeding",
    "breeding blanket",
    "plasma facing component",
    "plasma facing material",
    "edge localized mode",
    "tearing mode",
    "low energy nuclear reaction",
    "cold fusion",
    "muon catalyzed fusion",
    "proton boron fusion",
    "fusion fission hybrid",
    "liquid lithium",
    "lithium lead",
    "first wall",
    "target pellet",
    "cryogenic target",
]


PATENT_REPR_STOPWORDS = {
    "method",
    "device",
    "apparatus",
    "system",
    "structure",
    "assembly",
    "unit",
    "module",
    "component",
    "equipment",
    "mechanism",
    "process",
    "has",
    "comprises",
    "includes",
    "involves",
    "provided",
    "arranged",
    "connected",
    "configured",
    "formed",
    "mounted",
    "fixed",
    "used",
    "useful",
    "where",
    "which",
    "thereof",
    "for",
    "with",
    "and",
    "or",
    "of",
    "to",
    "in",
    "on",
    "by",
    "from",
    "as",
    "at",
    "into",
    "that",
    "is",
    "are",
    "be",
    "being",
    "having",
}
PATENT_REPR_STOPWORDS.update(ENGLISH_STOP_WORDS)
PATENT_REPR_STOPWORDS.update(
    {
        "abstract",
        "according",
        "drawing",
        "drawings",
        "dwg",
        "first",
        "noabstract",
        "said",
        "second",
    }
)


PATENT_ID_RE = re.compile(r"\b[A-Z]{2}\d{4,}[A-Z0-9]*(?:-[A-Z0-9]+)?\b")


def normalize_space(text: str) -> str:
    return re.sub(r"\s+", " ", text).strip()


def basic_clean(value: object) -> str:
    if pd.isna(value):
        return ""
    text = unicodedata.normalize("NFKC", str(value)).lower()
    text = text.replace("\u2010", "-").replace("\u2011", "-")
    text = text.replace("\u2012", "-").replace("\u2013", "-")
    text = text.replace("\u2014", "-").replace("\u2212", "-")
    text = re.sub(r"\b(?:e\.g|i\.e|etc)\.?\b", " ", text)
    text = text.replace("&", " and ")
    text = re.sub(r"(?<=\w)[/-](?=\w)", " ", text)
    text = re.sub(r"[^a-z0-9\s]", " ", text)
    return normalize_space(text)


def boundary_replace(text: str, mapping: dict[str, str]) -> str:
    result = text
    for source, target in sorted(mapping.items(), key=lambda item: len(item[0]), reverse=True):
        pattern = re.compile(r"(?<![a-z0-9_])" + re.escape(source) + r"(?![a-z0-9_])")
        result = pattern.sub(target, result)
    return normalize_space(result)


def conditional_term_normalize(text: str) -> str:
    result = text
    if any(word in result for word in FUSION_CONTEXT_WORDS):
        result = boundary_replace(
            result,
            {
                "deviation filter": "divertor",
                "offset filter": "divertor",
                "bias filter": "divertor",
            },
        )
    if any(word in result for word in BREEDING_CONTEXT_WORDS):
        result = boundary_replace(
            result,
            {
                "proliferation cladding": "breeding blanket",
                "tritium cladding": "breeding blanket",
                "cladding": "breeding blanket",
            },
        )
    return normalize_space(result)


def protect_phrases(text: str) -> str:
    result = text
    for phrase in sorted(PHRASES_TO_PROTECT, key=len, reverse=True):
        pattern = re.compile(r"(?<![a-z0-9_])" + re.escape(phrase) + r"(?![a-z0-9_])")
        result = pattern.sub(phrase.replace(" ", "_"), result)
    return normalize_space(result)


def repr_text_from_protected(text: str) -> str:
    terms = [term for term in text.split() if term not in PATENT_REPR_STOPWORDS]
    return " ".join(terms)


def preprocess_titles(df: pd.DataFrame, text_col: str) -> pd.DataFrame:
    out = df.copy()
    out["TI_raw"] = out[text_col].fillna("").astype(str)
    out["TI_clean"] = out["TI_raw"].map(basic_clean)
    out["TI_norm"] = (
        out["TI_clean"]
        .map(lambda text: boundary_replace(text, SPELLING_CORRECTIONS))
        .map(lambda text: boundary_replace(text, ABBREVIATIONS))
        .map(lambda text: boundary_replace(text, TERM_NORMALIZATION))
        .map(conditional_term_normalize)
    )
    protected = out["TI_norm"].map(protect_phrases)
    out["TI_embed_text"] = protected.str.replace("_", " ", regex=False)
    out["TI_repr_text"] = protected.map(repr_text_from_protected)
    return out


def preprocess_text_fields(df: pd.DataFrame, text_col: str, abstract_col: str | None) -> pd.DataFrame:
    out = preprocess_titles(df, text_col)
    if abstract_col and abstract_col in out.columns:
        out["AB_raw"] = out[abstract_col].fillna("").astype(str)
    else:
        out["AB_raw"] = ""
    out["AB_clean"] = out["AB_raw"].map(basic_clean)
    out["AB_norm"] = (
        out["AB_clean"]
        .map(lambda text: boundary_replace(text, SPELLING_CORRECTIONS))
        .map(lambda text: boundary_replace(text, ABBREVIATIONS))
        .map(lambda text: boundary_replace(text, TERM_NORMALIZATION))
        .map(conditional_term_normalize)
    )
    ab_protected = out["AB_norm"].map(protect_phrases)
    out["AB_embed_text"] = ab_protected.str.replace("_", " ", regex=False)
    out["AB_repr_text"] = ab_protected.map(repr_text_from_protected)

    out["patentbert_text"] = (
        out["TI_embed_text"].fillna("").astype(str).str.strip()
        + ". "
        + out["AB_embed_text"].fillna("").astype(str).str.strip()
    ).map(normalize_space)
    out["topic_repr_text"] = (
        out["TI_repr_text"].fillna("").astype(str).str.strip()
        + " "
        + out["AB_repr_text"].fillna("").astype(str).str.strip()
    ).map(normalize_space)
    return out


def choose_column(df: pd.DataFrame, candidates: list[str]) -> str | None:
    upper = {str(col).upper(): col for col in df.columns}
    for candidate in candidates:
        if candidate.upper() in upper:
            return upper[candidate.upper()]
    return None


def normalize_patent_id(value: str) -> str:
    text = unicodedata.normalize("NFKC", str(value)).upper()
    text = re.sub(r"[^A-Z0-9-]", "", text)
    return text


def patent_keys(value: str) -> set[str]:
    normalized = normalize_patent_id(value)
    if not normalized:
        return set()
    keys = {normalized}
    if "-" in normalized:
        keys.add(normalized.split("-", 1)[0])
    return keys


def extract_patent_ids(value: object) -> list[str]:
    if pd.isna(value):
        return []
    text = unicodedata.normalize("NFKC", str(value)).upper()
    return PATENT_ID_RE.findall(text)


def infer_forward_citations(raw: pd.DataFrame, kept_indices: np.ndarray) -> pd.Series:
    if "PN" not in raw.columns or "CP" not in raw.columns:
        return pd.Series(np.nan, index=np.arange(len(kept_indices)), dtype=float)

    patent_to_doc: dict[str, int] = {}
    for dedup_pos, raw_idx in enumerate(kept_indices):
        for patent_id in extract_patent_ids(raw.iloc[raw_idx]["PN"]):
            for key in patent_keys(patent_id):
                patent_to_doc.setdefault(key, dedup_pos)

    counts = np.zeros(len(kept_indices), dtype=float)
    for citing_pos, raw_idx in enumerate(kept_indices):
        cited_positions: set[int] = set()
        for cited_id in extract_patent_ids(raw.iloc[raw_idx]["CP"]):
            for key in patent_keys(cited_id):
                if key in patent_to_doc:
                    cited_positions.add(patent_to_doc[key])
        cited_positions.discard(citing_pos)
        for cited_pos in cited_positions:
            counts[cited_pos] += 1.0
    return pd.Series(counts)


def deduplicate_by_title(preprocessed: pd.DataFrame) -> tuple[pd.DataFrame, np.ndarray, pd.Series]:
    keys = preprocessed["TI_norm"].fillna("").astype(str).str.lower().str.replace(r"\s+", " ", regex=True).str.strip()
    empty = keys.eq("")
    keys.loc[empty] = "empty_title_" + pd.Series(np.arange(len(keys)), index=keys.index).astype(str)
    keep_mask = ~keys.duplicated(keep="first")
    kept_indices = np.flatnonzero(keep_mask.to_numpy())
    return preprocessed.iloc[kept_indices].reset_index(drop=True), kept_indices, keys


def build_dedup_docs(raw: pd.DataFrame, preprocessed: pd.DataFrame, kept_indices: np.ndarray) -> pd.DataFrame:
    kept_raw = raw.iloc[kept_indices].reset_index(drop=True)
    kept_pre = preprocessed.iloc[kept_indices].reset_index(drop=True)

    year_col = choose_column(
        raw,
        [
            "Publication Date",
            "Publication Year",
            "Earliest Publication Date",
            "Latest Publication Date",
            "PY",
            "YEAR",
            "PD",
            "PI_DATE",
            "FD",
        ],
    )
    citation_col = choose_column(
        raw,
        [
            "Cited by Patent Count",
            "CITED_BY_PATENT_COUNT",
            "CITED_BY",
            "TC",
            "CITATION",
            "CITATIONS",
        ],
    )
    ipc_col = choose_column(
        raw,
        [
            "IPCR Classifications",
            "IPC",
            "IP",
            "IPC_CODE",
            "IP_RAW",
            "IPC_CLASSES",
            "CPC Classifications",
            "CPC",
        ],
    )

    docs = pd.DataFrame()
    docs["doc_id"] = [safe_doc_id(kept_raw.iloc[i], i) for i in range(len(kept_raw))]
    docs["source_row_index"] = kept_indices
    for output_col, candidates in {
        "source_family_id": ["Family ID"],
        "source_representative_lens_id": ["Representative Lens ID"],
        "source_lens_id": ["Lens ID"],
        "source_display_key": ["Display Key", "Representative Display Key"],
        "source_jurisdiction": ["Jurisdiction"],
        "source_document_type": ["Document Type"],
        "source_legal_status": ["Legal Status"],
        "source_publication_date": ["Publication Date", "Earliest Publication Date"],
        "source_technical_feature": ["Technical Feature"],
        "source_technology_code": ["Technology Code"],
        "source_technology_label": ["Technology Label"],
        "source_route_code": ["Route Code"],
        "source_route_label": ["Route Label"],
        "source_chain_level1": ["Industry Chain Level 1"],
        "source_chain_level2": ["Industry Chain Level 2"],
        "source_chain_level3": ["Industry Chain Level 3"],
    }.items():
        source_col = choose_column(kept_raw, candidates)
        if source_col:
            docs[output_col] = kept_raw[source_col]
    docs["TI_raw"] = kept_pre["TI_raw"]
    docs["TI_clean"] = kept_pre["TI_clean"]
    docs["TI_norm"] = kept_pre["TI_norm"]
    docs["TI_embed_text"] = kept_pre["TI_embed_text"]
    docs["AB_raw"] = kept_pre["AB_raw"] if "AB_raw" in kept_pre.columns else ""
    docs["AB_clean"] = kept_pre["AB_clean"] if "AB_clean" in kept_pre.columns else ""
    docs["AB_norm"] = kept_pre["AB_norm"] if "AB_norm" in kept_pre.columns else ""
    docs["AB_embed_text"] = kept_pre["AB_embed_text"] if "AB_embed_text" in kept_pre.columns else ""
    docs["AB_repr_text"] = kept_pre["AB_repr_text"] if "AB_repr_text" in kept_pre.columns else ""
    docs["patentbert_text"] = (
        kept_pre["patentbert_text"] if "patentbert_text" in kept_pre.columns else kept_pre["TI_embed_text"]
    )
    # Keyword extraction uses the same document scope as clustering: TI + AB after representation cleanup.
    docs["TI_repr_text"] = (
        kept_pre["topic_repr_text"] if "topic_repr_text" in kept_pre.columns else kept_pre["TI_repr_text"]
    )

    docs["year"] = kept_raw[year_col].map(parse_year) if year_col else np.nan
    if citation_col:
        docs["citation_count"] = pd.to_numeric(kept_raw[citation_col], errors="coerce")
        docs["citation_count_source"] = citation_col
    else:
        docs["citation_count"] = infer_forward_citations(raw, kept_indices)
        docs["citation_count_source"] = "in_corpus_forward_from_CP"

    docs["ipc_raw"] = kept_raw[ipc_col] if ipc_col else np.nan
    parsed_ipc = docs["ipc_raw"].map(parse_ipc_subclasses)
    docs["ipc_subclasses"] = parsed_ipc.map(subclasses_to_text)
    docs["_ipc_list"] = parsed_ipc
    return docs


def resolve_text_columns(raw: pd.DataFrame, text_col: str, abstract_col: str) -> tuple[str, str | None]:
    resolved_text_col = text_col if text_col in raw.columns else None
    if resolved_text_col is None:
        resolved_text_col = choose_column(raw, ["Title", "TI", "TITLE"])
    if resolved_text_col is None:
        raise ValueError(
            f"Text column {text_col!r} was not found, and no Title/TI fallback column exists."
        )

    resolved_abstract_col = abstract_col if abstract_col in raw.columns else None
    if resolved_abstract_col is None:
        resolved_abstract_col = choose_column(raw, ["Abstract", "AB", "ABSTRACT"])
    return resolved_text_col, resolved_abstract_col


def safe_name(value: str) -> str:
    return re.sub(r"[^a-zA-Z0-9_.-]+", "_", value).strip("_")[:120]


def text_signature(texts: list[str]) -> str:
    digest = hashlib.sha1()
    for text in texts:
        digest.update(str(text).encode("utf-8", errors="ignore"))
        digest.update(b"\n")
    return digest.hexdigest()[:12]


def choose_device(device: str) -> str:
    if device != "auto":
        return device
    import torch

    return "cuda" if torch.cuda.is_available() else "cpu"


def mean_pool(last_hidden_state, attention_mask):
    import torch

    mask = attention_mask.unsqueeze(-1).expand(last_hidden_state.size()).to(last_hidden_state.dtype)
    summed = torch.sum(last_hidden_state * mask, dim=1)
    counts = torch.clamp(mask.sum(dim=1), min=1e-9)
    return summed / counts


def encode_with_transformers(
    texts: list[str],
    model_name: str,
    device: str,
    batch_size: int,
    max_seq_length: int,
) -> np.ndarray:
    import torch
    from transformers import AutoModel, AutoTokenizer

    tokenizer = AutoTokenizer.from_pretrained(model_name)
    model = AutoModel.from_pretrained(model_name)
    model.to(device)
    use_bfloat16 = device == "cpu" and os.environ.get("FUSION_BERT_DTYPE", "").lower() in {"bf16", "bfloat16"}
    if use_bfloat16:
        model.to(dtype=torch.bfloat16)
    model.eval()

    lengths = tokenizer(
        texts,
        padding=False,
        truncation=True,
        max_length=max_seq_length,
        return_length=True,
    )["length"]
    order = sorted(range(len(texts)), key=lengths.__getitem__)
    sorted_lengths = [int(lengths[index]) for index in order]
    vectors = np.empty((len(texts), int(model.config.hidden_size)), dtype=np.float32)
    processed = 0
    cursor = 0
    while cursor < len(order):
        first_length = max(1, int(lengths[order[cursor]]))
        if first_length <= 64:
            dynamic_batch_size = min(512, batch_size * 4)
            length_ceiling = 64
        elif first_length <= 128:
            dynamic_batch_size = min(384, batch_size * 2)
            length_ceiling = 128
        elif first_length <= 192:
            dynamic_batch_size = min(256, max(batch_size, batch_size * 4 // 3))
            length_ceiling = 192
        else:
            dynamic_batch_size = batch_size
            length_ceiling = max_seq_length
        group_end = bisect_right(sorted_lengths, length_ceiling, lo=cursor)
        selected = order[cursor : min(cursor + dynamic_batch_size, group_end)]
        batch = [texts[index] for index in selected]
        encoded = tokenizer(
            batch,
            padding=True,
            truncation=True,
            max_length=max_seq_length,
            return_tensors="pt",
        )
        encoded = {key: value.to(device) for key, value in encoded.items()}
        autocast = torch.autocast("cpu", dtype=torch.bfloat16) if use_bfloat16 else nullcontext()
        with torch.no_grad(), autocast:
            output = model(**encoded)
            pooled = mean_pool(output.last_hidden_state, encoded["attention_mask"])
        pooled = torch.nn.functional.normalize(pooled.float(), p=2, dim=1)
        vectors[np.asarray(selected, dtype=int)] = pooled.cpu().numpy()
        cursor += len(selected)
        processed += len(selected)
        print(f"Encoded {processed}/{len(texts)}")
    return vectors


def encode_with_sentence_transformers(
    texts: list[str],
    model_name: str,
    device: str,
    batch_size: int,
    max_seq_length: int,
) -> np.ndarray:
    from sentence_transformers import SentenceTransformer

    model = SentenceTransformer(model_name, device=device)
    if max_seq_length and hasattr(model, "max_seq_length"):
        model.max_seq_length = max_seq_length
    return model.encode(
        texts,
        batch_size=batch_size,
        show_progress_bar=True,
        convert_to_numpy=True,
        normalize_embeddings=True,
    )


def encode_texts(
    texts: list[str],
    model_name: str,
    backend: str,
    device: str,
    batch_size: int,
    max_seq_length: int,
) -> np.ndarray:
    actual_device = choose_device(device)
    if backend in {"auto", "sentence-transformers"}:
        try:
            return encode_with_sentence_transformers(
                texts=texts,
                model_name=model_name,
                device=actual_device,
                batch_size=batch_size,
                max_seq_length=max_seq_length,
            )
        except Exception as exc:
            if backend == "sentence-transformers":
                raise
            print(f"SentenceTransformer loading failed ({exc}); trying transformers mean pooling.")
    return encode_with_transformers(
        texts=texts,
        model_name=model_name,
        device=actual_device,
        batch_size=batch_size,
        max_seq_length=max_seq_length,
    )


def load_or_create_ti_ab_embeddings(
    docs: pd.DataFrame,
    args: argparse.Namespace,
    output_dir: Path,
) -> tuple[np.ndarray, Path]:
    texts = docs["patentbert_text"].fillna("").astype(str).tolist()
    signature = text_signature(texts)
    emb_path = output_dir / (
        f"ti_ab_patentbert_embeddings_{safe_name(args.model_name)}_{len(texts)}_{signature}.npy"
    )
    if args.reuse_embeddings and emb_path.exists():
        print(f"Loading cached TI+AB PatentBERT embeddings: {emb_path}")
        return np.load(emb_path), emb_path

    print(f"Encoding {len(texts)} deduplicated TI+AB texts with {args.model_name}")
    embeddings = encode_texts(
        texts=texts,
        model_name=args.model_name,
        backend=args.embedding_backend,
        device=args.device,
        batch_size=args.batch_size,
        max_seq_length=args.max_seq_length,
    )
    embeddings = np.asarray(embeddings, dtype=np.float32)
    np.save(emb_path, embeddings)
    return embeddings, emb_path


def cluster_with_umap_hdbscan(
    embeddings: np.ndarray,
    n_neighbors: int,
    n_components: int,
    min_dist: float,
    min_cluster_size: int,
    min_samples: int,
    random_state: int,
) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    print("Importing UMAP and HDBSCAN only for clustering...")
    import hdbscan
    import umap

    reducer = umap.UMAP(
        n_neighbors=n_neighbors,
        n_components=n_components,
        min_dist=min_dist,
        metric="cosine",
        random_state=random_state,
    )
    umap_embeddings = reducer.fit_transform(embeddings)

    clusterer = hdbscan.HDBSCAN(
        min_cluster_size=min_cluster_size,
        min_samples=min_samples,
        metric="euclidean",
        cluster_selection_method="eom",
        prediction_data=True,
    )
    labels = clusterer.fit_predict(umap_embeddings).astype(int)
    probabilities = getattr(clusterer, "probabilities_", np.full(len(labels), np.nan))
    return labels, probabilities, umap_embeddings


def relabel_small_topics_as_noise(docs: pd.DataFrame, min_valid_topic_size: int) -> dict[str, int]:
    min_size = max(1, int(min_valid_topic_size))
    counts = docs["topic_id"].value_counts(dropna=False)
    non_noise_counts = counts[counts.index != -1]
    small_topics = sorted(int(topic) for topic, size in non_noise_counts.items() if int(size) < min_size)
    small_mask = docs["topic_id"].isin(small_topics)

    docs["topic_id_raw"] = docs["topic_id"].astype(int)
    docs["raw_topic_size"] = docs["topic_id_raw"].map(counts).fillna(0).astype(int)
    docs["is_small_topic_noise"] = small_mask
    if small_topics:
        docs.loc[small_mask, "topic_id"] = -1
        docs.loc[small_mask, "topic_probability"] = 0.0
    docs["is_bertopic_outlier"] = docs["topic_id"].eq(-1)

    filtered_counts = docs["topic_id"].value_counts(dropna=False)
    return {
        "min_valid_topic_size": min_size,
        "hdbscan_topic_count_excluding_minus_1": int((non_noise_counts.index != -1).sum()),
        "hdbscan_topic_count_including_minus_1": int(counts.shape[0]),
        "small_topic_count_relabelled": int(len(small_topics)),
        "small_topic_doc_count_relabelled": int(small_mask.sum()),
        "topic_count_excluding_minus_1_after_filter": int(sum(1 for topic in filtered_counts.index if int(topic) != -1)),
        "topic_count_including_minus_1_after_filter": int(filtered_counts.shape[0]),
        "noise_doc_count_after_filter": int(docs["topic_id"].eq(-1).sum()),
    }


def make_run_log(
    input_path: Path,
    embedding_path: Path,
    output_path: Path,
    raw_rows: int,
    dedup_rows: int,
    duplicate_rows: int,
    docs: pd.DataFrame,
    raw_indicators: pd.DataFrame,
    args: argparse.Namespace,
    topic_filter_stats: dict[str, int],
) -> pd.DataFrame:
    deepseek_filter_stats = docs.attrs.get("deepseek_relevance_filter_stats", {})
    entries = {
        "input_path": str(input_path),
        "embedding_path": str(embedding_path),
        "output_path": str(output_path),
        "raw_rows": int(raw_rows),
        "deduplicated_rows": int(dedup_rows),
        "removed_duplicate_rows": int(duplicate_rows),
        "dedup_key": "TI_norm",
        "source_sheet": args.sheet,
        "source_field_mapping": "Title->TI, Abstract->AB, Publication Date->year, Cited by Patent Count->citation_count, IPCR Classifications->ipc",
        "embedding_mode": "PatentBERT/PatentSBERT encoded from TI + AB after deduplication",
        "embedding_text_field": "patentbert_text",
        "model_name": args.model_name,
        "max_seq_length": int(args.max_seq_length),
        "topic_pipeline": "dedup -> preprocess TI+AB -> PatentBERT embeddings -> UMAP -> HDBSCAN -> DeepSeek topic sentence extraction and fusion-relevance filtering -> indicators",
        "topic_representation": "DeepSeek generates sentence-level topic summaries and filters topics that are clearly unrelated to nuclear fusion.",
        "deepseek_model": args.deepseek_model,
        "deepseek_base_url": args.deepseek_base_url,
        "deepseek_api_key_env": args.deepseek_api_key_env,
        "deepseek_topic_cache": str(data_path(args.deepseek_topic_cache)),
        "deepseek_topic_schema_version": int(DEEPSEEK_TOPIC_SCHEMA_VERSION),
        "deepseek_topic_docs": int(args.deepseek_topic_docs),
        "deepseek_timeout": int(args.deepseek_timeout),
        "deepseek_retries": int(args.deepseek_retries),
        "umap_n_neighbors": int(args.umap_neighbors),
        "umap_n_components": int(args.umap_components),
        "umap_min_dist": float(args.umap_min_dist),
        "hdbscan_min_cluster_size": int(args.min_topic_size),
        "hdbscan_min_samples": int(args.min_samples),
        "min_valid_topic_size": int(topic_filter_stats["min_valid_topic_size"]),
        "hdbscan_topic_count_excluding_minus_1": int(topic_filter_stats["hdbscan_topic_count_excluding_minus_1"]),
        "hdbscan_topic_count_including_minus_1": int(topic_filter_stats["hdbscan_topic_count_including_minus_1"]),
        "small_topic_count_relabelled": int(topic_filter_stats["small_topic_count_relabelled"]),
        "small_topic_doc_count_relabelled": int(topic_filter_stats["small_topic_doc_count_relabelled"]),
        "topic_count_excluding_minus_1_after_filter": int(topic_filter_stats["topic_count_excluding_minus_1_after_filter"]),
        "topic_count_including_minus_1_after_filter": int(topic_filter_stats["topic_count_including_minus_1_after_filter"]),
        "noise_doc_count_after_filter": int(topic_filter_stats["noise_doc_count_after_filter"]),
        "deepseek_non_fusion_topic_count": int(deepseek_filter_stats.get("deepseek_non_fusion_topic_count", 0)),
        "deepseek_non_fusion_doc_count": int(deepseek_filter_stats.get("deepseek_non_fusion_doc_count", 0)),
        "topic_count_excluding_minus_1_after_deepseek_filter": int(
            deepseek_filter_stats.get(
                "topic_count_excluding_minus_1_after_deepseek_filter",
                docs.loc[docs["topic_id"].ne(-1), "topic_id"].nunique(),
            )
        ),
        "noise_doc_count_after_deepseek_filter": int(
            deepseek_filter_stats.get("noise_doc_count_after_deepseek_filter", docs["topic_id"].eq(-1).sum())
        ),
        "topic_count_including_minus_1": int(raw_indicators["topic_id"].nunique()),
        "outlier_doc_count_topic_minus_1": int(docs["topic_id"].eq(-1).sum()),
        "year_parsed_rows": int(docs["year"].notna().sum()),
        "citation_parsed_rows": int(docs["citation_count"].notna().sum()),
        "ipc_subclass_parsed_rows": int(docs["_ipc_list"].map(bool).sum()),
    }
    for col in [
        "impact_raw",
        "novelty_raw",
        "short_trend_raw",
        "long_trend_raw",
        "centrality_raw",
        "cross_domain_raw",
        "lof_raw",
    ]:
        entries[f"{col}_topic_count"] = int(raw_indicators[col].notna().sum())
    return pd.DataFrame({"key": list(entries.keys()), "value": list(entries.values())})


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Deduplicate patents, recluster with PatentBERT/UMAP/HDBSCAN, use DeepSeek to extract sentence-level topic summaries, then score topics."
    )
    parser.add_argument("--input", type=Path, default=DEFAULT_MERGED_PATENTS_PATH)
    parser.add_argument("--sheet", default=DEFAULT_MERGED_FAMILIES_SHEET)
    parser.add_argument("--text-col", default="Title")
    parser.add_argument("--abstract-col", default="Abstract")
    parser.add_argument("--model-name", default="AI-Growth-Lab/PatentSBERTa")
    parser.add_argument("--embedding-backend", choices=["auto", "sentence-transformers", "transformers"], default="auto")
    parser.add_argument("--device", default="auto")
    parser.add_argument("--batch-size", type=int, default=16)
    parser.add_argument("--max-seq-length", type=int, default=256)
    parser.add_argument("--reuse-embeddings", action=argparse.BooleanOptionalAction, default=True)
    parser.add_argument("--embedding-output-dir", type=Path, default=data_path("fusion_ti_outputs"))
    parser.add_argument("--output", type=Path, default=DEFAULT_MERGED_FAMILIES_OUTPUT)
    parser.add_argument("--umap-neighbors", type=int, default=15)
    parser.add_argument("--umap-components", type=int, default=5)
    parser.add_argument("--umap-min-dist", type=float, default=0.0)
    parser.add_argument("--min-topic-size", type=int, default=10)
    parser.add_argument("--min-samples", type=int, default=5)
    parser.add_argument("--min-valid-topic-size", type=int, default=DEFAULT_MIN_VALID_TOPIC_SIZE)
    parser.add_argument("--recent-window", type=int, default=5)
    parser.add_argument("--min-year-points", type=int, default=4)
    parser.add_argument("--random-state", type=int, default=42)
    parser.add_argument("--deepseek-model", default="deepseek-v4-flash")
    parser.add_argument("--deepseek-base-url", default="https://api.deepseek.com")
    parser.add_argument("--deepseek-api-key-env", default="DEEPSEEK_API_KEY")
    parser.add_argument("--deepseek-topic-cache", type=Path, default=DEFAULT_DEEPSEEK_TOPIC_CACHE)
    parser.add_argument("--deepseek-topic-docs", type=int, default=10)
    parser.add_argument("--deepseek-timeout", type=int, default=120)
    parser.add_argument("--deepseek-retries", type=int, default=2)
    parser.add_argument("--deepseek-workers", type=int, default=1)
    parser.add_argument(
        "--local-topic-summaries",
        action="store_true",
        help="Generate deterministic topic text from IncoPat labels instead of calling an external model.",
    )
    parser.add_argument("--refresh-deepseek-topics", action="store_true")
    parser.add_argument(
        "--all-topics-related",
        action="store_true",
        help="Keep every clustered topic instead of applying the non-fusion relevance filter.",
    )
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    input_path = data_path(args.input)
    output_path = output_path_for_new_file(data_path(args.output))
    embedding_output_dir = data_path(args.embedding_output_dir)
    args.embedding_output_dir = embedding_output_dir
    embedding_output_dir.mkdir(parents=True, exist_ok=True)

    print(f"Reading input: {input_path}")
    raw = read_table(input_path, args.sheet)
    text_col, abstract_col = resolve_text_columns(raw, args.text_col, args.abstract_col)
    print(f"Using text column: {text_col}")
    print(f"Using abstract column: {abstract_col or 'none'}")
    if abstract_col is None:
        print(f"Abstract column {args.abstract_col!r} was not found; PatentBERT text will use TI only.")

    print("Preprocessing TI and AB...")
    preprocessed = preprocess_text_fields(raw, text_col, abstract_col)
    _, kept_indices, _ = deduplicate_by_title(preprocessed)
    docs = build_dedup_docs(raw, preprocessed, kept_indices)
    duplicate_rows = len(raw) - len(docs)
    print(f"Deduplicated rows: {len(docs)} / {len(raw)}; removed duplicates: {duplicate_rows}")

    dedup_embeddings, embedding_path = load_or_create_ti_ab_embeddings(
        docs=docs,
        args=args,
        output_dir=embedding_output_dir,
    )

    print("Running UMAP -> HDBSCAN on deduplicated embeddings...")
    labels, probabilities, umap_embeddings = cluster_with_umap_hdbscan(
        embeddings=dedup_embeddings,
        n_neighbors=args.umap_neighbors,
        n_components=args.umap_components,
        min_dist=args.umap_min_dist,
        min_cluster_size=args.min_topic_size,
        min_samples=args.min_samples,
        random_state=args.random_state,
    )
    docs["topic_id"] = labels
    docs["is_bertopic_outlier"] = docs["topic_id"].eq(-1)
    docs["topic_probability"] = probabilities
    for component in range(umap_embeddings.shape[1]):
        docs[f"UMAP_{component + 1}"] = umap_embeddings[:, component]

    topic_filter_stats = relabel_small_topics_as_noise(docs, args.min_valid_topic_size)
    print(
        "HDBSCAN topics before small-topic noise filter: "
        f"{topic_filter_stats['hdbscan_topic_count_excluding_minus_1']} non-noise topics "
        f"({topic_filter_stats['hdbscan_topic_count_including_minus_1']} including -1)."
    )
    print(
        f"Relabelled topics with fewer than {topic_filter_stats['min_valid_topic_size']} patent families as noise: "
        f"{topic_filter_stats['small_topic_count_relabelled']} topics, "
        f"{topic_filter_stats['small_topic_doc_count_relabelled']} patent families."
    )
    print(
        "Topics after small-topic noise filter: "
        f"{topic_filter_stats['topic_count_excluding_minus_1_after_filter']} non-noise topics "
        f"({topic_filter_stats['topic_count_including_minus_1_after_filter']} including -1); "
        f"noise patents: {topic_filter_stats['noise_doc_count_after_filter']}."
    )

    print("Computing DeepSeek topic sentence summaries and seven topic indicators...")
    raw_indicators, normalized, year_counts, topic_embeddings = compute_indicator_tables(
        docs=docs,
        embeddings=dedup_embeddings,
        recent_window=args.recent_window,
        min_year_points=args.min_year_points,
        args=args,
    )
    topic_keyword_cols = [
        "topic_id",
        "topic_size",
        "is_bertopic_outlier",
        "topic_keywords",
        "route_name_cn",
        "route_name_en",
        "topic_summary",
        "topic_description",
        "technology_route_sentences",
        "evidence_sentences",
        "fusion_industry_chain_position",
        "fusion_industry_chain_relation",
        "fusion_application_scenarios",
        "is_fusion_related",
        "fusion_relevance",
        "fusion_relevance_reason",
        "confidence",
        "deepseek_status",
        "deepseek_model",
        "deepseek_cache_key",
        "representative_docs",
    ]
    topic_keywords = raw_indicators[[col for col in topic_keyword_cols if col in raw_indicators.columns]].copy()
    run_log = make_run_log(
        input_path=input_path,
        embedding_path=embedding_path,
        output_path=output_path,
        raw_rows=len(raw),
        dedup_rows=len(docs),
        duplicate_rows=duplicate_rows,
        docs=docs,
        raw_indicators=raw_indicators,
        args=args,
        topic_filter_stats=topic_filter_stats,
    )

    print(f"Writing one workbook: {output_path}")
    write_workbook(
        output_path=output_path,
        docs=docs,
        topic_keywords=topic_keywords,
        year_counts=year_counts,
        raw=raw_indicators,
        normalized=normalized,
        topic_embeddings=topic_embeddings,
        run_log=run_log,
    )

    print(f"Topic count excluding -1: {int(raw_indicators['topic_id'].ne(-1).sum())}")
    print(f"Topic count including -1: {raw_indicators['topic_id'].nunique()}")
    print(f"Topic -1 document count: {int(docs['topic_id'].eq(-1).sum())}")
    print(f"Finished: {output_path}")


if __name__ == "__main__":
    main()
